### ISSUE TITLE
Migration to Tailwind CSS v4.0 Beta

### ISSUE THREAD

**Issue by alamonatalia** [Forever-twenty-nine/ftn-site#6]
Hay problemas porque "@astrojs/tailwind@5.1.2" aún depende de "tailwindcss@3.0.24" para funcionar entonces al actualizar tailwind se presentan errores por ejemplo con el postcss que ya no se usa e igual lo sigue buscando y demás yerbas raras.

Una solución sería eliminar "@astrojs/tailwind..." y hacer la configuración de tailwind a mano. El problema es que tengo que compilar cada vez que agrego clases, variables para que se genere el nuevo css y es caca porque pierdo tiempo. 

Opino @sebasechazu que avancemos con esta versión de Tailwind 3 y cuando Astro dé soporte a Tailwind 4 avanzar con la migración porque ellos proponen una herramienta para que se haga la migración automáticamente y es muy buena ya que no tenes que hacer nada de nada. Te parece?

**Comment by sebasechazu** [comment]
perfecto esto es muy reciente asi que continuemos asi @alamonatalia.
